### ISSUE TITLE
Compilation problem with Eigen

### ISSUE THREAD

**Issue by Kyrish** [kthohr/stats#11]
Hi! First of all, I'd like to thank for the great library! I'm playing around with the library and got following issue. My sample code is:

```C++
#include <iostream>
#include "stats.hpp"
#include <Eigen/Dense>

#define STATS_USE_EIGEN

int main() {

    Eigen::MatrixXd gamma_rvs = stats::rgamma<Eigen::MatrixXd>(100,50,3.0,2.0);
    std::cout << gamma_rvs << std::endl;

    return 0;
}
```

And compilation gave me:

 

> /usr/local/bin/cmake --build /Users/alex/Development/stats_tests/cmake-build-debug --target stats_tests -- -j 4
Scanning dependencies of target stats_tests
[ 50%] Building CXX object CMakeFiles/stats_tests.dir/main.cpp.o
In file included from /Users/alex/Development/stats_tests/include/rand/rand.hpp:27:0,
                 from /Users/alex/Development/stats_tests/include/stats.hpp:37,
                 from /Users/alex/Development/stats_tests/main.cpp:2:
/Users/alex/Development/stats_tests/include/rand/rgamma.hpp:42:4: warning: inline function 'mT stats::rgamma(stats::uint_t, stats::uint_t, eT, eT) [with mT = Eigen::Matrix<double, -1, -1>; eT = double; stats::uint_t = unsigned int]' used but never defined
 mT rgamma(const uint_t n, const uint_t k, const eT shape_par, const eT scale_par);
    ^~~~~~
[100%] Linking CXX executable stats_tests
Undefined symbols for architecture x86_64:
  "Eigen::Matrix<double, -1, -1, 0, -1, -1> stats::rgamma<Eigen::Matrix<double, -1, -1, 0, -1, -1>, double>(unsigned int, unsigned int, double, double)", referenced from:
      _main in main.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[3]: *** [stats_tests] Error 1
make[2]: *** [CMakeFiles/stats_tests.dir/all] Error 2
make[1]: *** [CMakeFiles/stats_tests.dir/rule] Error 2
make: *** [stats_tests] Error 2

Could you please help me to figure out what's going on.
Thanks!
Alex

**Comment by Kyrish** [comment]
Dear @kthohr, thanks! It works. Was a stupid mistake on my part.

**Comment by kthohr** [comment]
Glad to hear it works now.
