### ISSUE TITLE
dunif returns a non-zero value outside of the bounds

### ISSUE THREAD

**Issue by somu15** [kthohr/stats#12]
Hi there!

Thanks for the stats codes, very helpful. I've found that the uniform distributions density function (dunif) returns a non-zero value even when the random variable is outside of the bounds. For example, consider the uniform distribution unif(0.1, 0.2). A random variable with value 0.15 will have density 10, and if the RV value is 0.201 its density should be 0, theoretically. I found that the current implementation of dunif might not meet this criterion.

Best,

**Comment by kthohr** [comment]
Fixed with the new version; more guardrails have been added.
