### ISSUE TITLE
Multivariate normal with Eigen

### ISSUE THREAD

**Issue by gpanders** [kthohr/stats#13]
I am not quite sure how to use the multivariate normal distribution function using Eigen. The signature of the function appears to expect `X`, `mu_par`, and `Sigma_par` to all have the same type; however, in Eigen there is no generic "matrix" class (as there appears to be for Armadillo, according to the [documentation](https://www.kthohr.com/statslib_docs_mvnorm.html)) but each value has a specified size, i.e.

```cpp
Eigen::Matrix<double, 3, 1> X(1, 1, 1);
Eigen::Matrix<double, 3, 1> mean(0, 0, 0);
Eigen::Matrix<double, 3, 3> Sigma = Eigen::Matrix3d::Identity();

// Or, more succinctly
// Eigen::Vector3d X(1, 1, 1);
// Eigen::Vector3d mean(0, 0, 0);
// Eigen::Matrix3d Sigma = Eigen::Matrix3d::Identity();

p = stats::dmvnorm(X, mean, Sigma);
```

This fails to compile with the following:

```clang
main.cpp:11:16: error: no matching function for call to 'dmvnorm'
  std::cout << stats::dmvnorm(X, mean, Sigma) << std::endl;
               ^~~~~~~~~~~~~~
./include/dens/dmvnorm.ipp:28:1: note: candidate template ignored: deduced conflicting types for parameter 'mT' ('Matrix<[2 * ...], 1, [2 * ...], 1>' vs. 'Matrix<[2 * ...], 3, [2 * ...], 3>')
dmvnorm(const mT& X, const mT& mu_par, const mT& Sigma_par, bool log_form)
^
1 error generated.
```

How do I go about using the multivariate functions with Eigen?

**EDIT**: I am able to get the above example to compile using the `Eigen::MatrixXd` classes which does serve as a "generic" matrix class. This will work for me. However, out of curiosity is there a way to use the stats library with compile-time Eigen sizes (like in my example)? Eigen recommends using fixed sizes known at compile time for small matrices and I would like to take advantage of those optimizations if possible.

**Comment by kthohr** [comment]
Thanks for the pointer. I have modified the internals and your example should compile now.
