### ISSUE TITLE
Does it contain Generalized extreme value distribution also?

### ISSUE THREAD

**Issue by JeyP4** [kthohr/stats#14]
Does it contain Generalized extreme value distribution also?
![image](https://user-images.githubusercontent.com/44414900/56078786-53235400-5dec-11e9-9f06-ce355f450dc1.png)

E.g.
dataN = [5.44030563610939, 10.7071212794335, 6.98863965149785, 5.75855288152361, 4.35389980467031, 6.65717299986184,
         6.23022372943957, 4.61731971899753, 8.78179518233592, 5.68478054008583, 5.20860732492683, 4.21808687299822,
         8.64324644243904, 5.15451105578527, 7.03633883643414, 9.30334793245299, 5.40342918996923, 5.89134257860982,
         6.89237263218421, 5.00530206799751]
Matlab :
param = gevfit(dataN);

**Comment by kthohr** [comment]
No. Feel free to create a PR.
