### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by Vagabond** [kthohr/stats#15]
It'd be great to have some tags for the release versions like 2.2.0.

**Comment by kthohr** [comment]
Releases after version 3.0.0 will be tagged. It’s been work in progress for a while.

**Comment by Vagabond** [comment]
Would it be possible to retroactively tag the 2.2.0 commit? I'd like to pin this repo as a dependency and I'd rather not just track master.

**Comment by kthohr** [comment]
I will tag 3.0.0 in the coming days. Can you check if anything breaks with the new version?

**Comment by Vagabond** [comment]
Sure, thanks!

**Comment by Vagabond** [comment]
There's still not a 3.0.0 tag, what is the best commit to use to pin as a dependency?

Additionally what commit or tag (I note GCEM has tags) should I use with the designated commit of stats?

**Comment by kthohr** [comment]
Tagged with the new release.
