### ISSUE TITLE
Documentation. Samples.

### ISSUE THREAD

**Issue by DJuego** [kthohr/stats#2]
Thanks for sharing your work! 

It would be interesting to document the library and provide examples. At least list supported distribution functions and features. 

Thanks again!

DJuego

**Comment by kthohr** [comment]
Yes, this is a good idea---I've just been too lazy to do it!

A list of available distributions is in the readme file now. I'll add more details this week.

**Comment by DJuego** [comment]
Thank you for your efforts!  I am keeping an eye on this library.  :-)

P.S: 

There is a typo in the comments of your Examples 
evaulate -> evaluate

**Comment by kthohr** [comment]
Whoops! Fixed now.

**Comment by kthohr** [comment]
I've expanded the readme file and added some additional examples. Should be enough for now.

**Comment by DJuego** [comment]
Thank you, @kthohr!

DJuego
