### ISSUE TITLE
passing vectors to qnorm()

### ISSUE THREAD

**Issue by alexhallam** [kthohr/stats#20]
It is not obvious to me what the syntax is for passing a vector of probabilities to `stats::qnorm()`. How would I replicate this R code.

```
a = qnorm(p= c(0.01, 0.20, 0.50, 0.80, 0.99))
```

I was able to pass single values to `stats::qnorm`, but got errors when I would attempt to pass a vector.

**Comment by kthohr** [comment]
What do you mean by 'vector' here? If you are referring to a `std::vector` object, then the [documentation](https://statslib.readthedocs.io/en/latest/api/normal.html#id9) provides an example:

```
std::vector<double> x = {0.1, 0.3, 0.7};
stats::qnorm(x,1.0,2.0,false);
```

**Comment by alexhallam** [comment]
Looks like I may have a deeper issue. I copied your code and still had issues. This is my file.

```
#include <iostream>
#include <armadillo>
#include "heads/stats/include/stats.hpp"

using namespace std;
using namespace arma;

int
main(int argc, char** argv)
  {

  std::vector<double> x = {0.1, 0.3, 0.7};
  stats::qnorm(x, 0.0, 1.0, false);
return 0;
}
```

`gcc` found an error in the header. 

```
In file included from heads/stats/include/stats_incl/quant/qnorm.hpp:80,
                 from heads/stats/include/stats_incl/quant/quant.hpp:35,
                 from heads/stats/include/stats.hpp:35,
                 from <stdin>:3:
heads/stats/include/stats_incl/quant/qnorm.ipp:117:1: note: candidate: ‘template<class T> constexpr stats::return_t<T> stats::qnorm(T)’
 qnorm(const T p)
 ^~~~~
heads/stats/include/stats_incl/quant/qnorm.ipp:117:1: note:   template argument deduction/substitution failed:
```

and 

```
no matching function for call to 'qnorm(std::vector<double>&, double, double, bool)'
```

I am still learning C++ so if this is basic stuff I apologize.

**Comment by kthohr** [comment]
You did not enable the `std:vector` wrappers. All wrapper code for vector/matrix libraries is disabled by default to reduce code bloat.

Try this:

```cpp
#include <iostream>

#define STATS_ENABLE_STDVEC_WRAPPERS
#include "heads/stats/include/stats.hpp"

int
main(int argc, char** argv)
{
    std::vector<double> x = {0.1, 0.3, 0.7};
    std::vector<double> y = stats::qnorm(x, 0.0, 1.0);

    std::cout << y[0] << std::endl;

    return 0;
}

```

Compiler options like this are discussed in the [documentation](https://statslib.readthedocs.io/en/latest/compiler_options.html).
