### ISSUE TITLE
Please allow specification of the random number generator implementation

### ISSUE THREAD

**Issue by adamfowleruk** [kthohr/stats#31]
I'm working on a project where I need to keep backwards compatibility with GSL's behaviour in an application but use code under an Apache-2.0 license. I need to use the mt19937 with a particular seed rather than the mt19937_64 rng. Currently I believe the only way of doing this in the stats library is editing the stats_options.hpp file to use mt19937, set my own seed, and then ensuring I pass in a smaller type (i.e. floats rather than double) to functions I call to ensure the random number generator is used the same way, and generates the same sequence of numbers for testing. This works for most functions (although some, deep down, use larger types than I need and thus generates a difference sequence - but this isn't common). This does mean forcing downstream users to fetch and edit this options.hpp file, which will likely cause confusion.

If you currently have a way of overriding the random number generator without editing the stats_options.hpp file that'd be great to understand. If not, please let me know, and I'll add in a new option define, test it, and contribute it back as a PR. Please let me know how you'd like me to proceed.

It's a great library. I hope to use the OpenMP functionality soon too. Thanks for the hard work!

**Comment by kthohr** [comment]
I just added the ability to do this by defining `STATS_RNG_ENGINE_TYPE`. See:

https://github.com/kthohr/stats/blob/master/include/stats_incl/misc/statslib_options.hpp#L59

**Comment by adamfowleruk** [comment]
Wonderful, thanks!
