### ISSUE TITLE
compiling with MSVC

### ISSUE THREAD

**Issue by rlatowicz** [kthohr/stats#8]
Hi Keith,
Thanks for sharing your library.

Changing the define at the bottom of  **statslib_options.hpp**,
from:
`#define __stats_pointer_settings__ __restrict__`

to:
`#define __stats_pointer_settings__ __restrict`

will make the library compatible with MSVC as well as GCC/Clang.

Thanks again,
Rafael.

**Comment by kthohr** [comment]
Hi @rlatowicz 

Let me know if the new version works for you.

https://github.com/kthohr/stats/blob/eb11e2dde61ff23c15d20d4ce4811c1bb7352537/include/misc/statslib_options.hpp#L136-L144

**Comment by rlatowicz** [comment]
That's great.

I wasn't as clear as I could have been.
GCC & Clang are happy with either,
`__restrict__`
or
`__restrict`

See here:
https://gcc.gnu.org/onlinedocs/gcc/Restricted-Pointers.html

So using,
`__restrict`

will work with GCC, Clang & MSVC.
No need to differentiate.

Thanks again.
Greatly appreciated.

**Comment by kthohr** [comment]
Hmm. I've experienced different behavior with Clang in the past, but perhaps this is not longer the case. I'll leave it as-is for now but thanks for alerting me to this!
